/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.appreactor.ahorcado;

import co.appreactor.ahorcado.modelo.Palabras;
import co.appreactor.ahorcado.negocio.Comparador;
import java.awt.GridBagLayout;
import java.util.Random;
import javax.swing.JTextField;

/**
 *
 * @author Lord_Nightmare
 */
public class Principal extends javax.swing.JFrame {

    private int intentos;
    private String palabra;
    private Comparador comp;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Juego del Ahorcado");
        plPalabra.setLayout(new GridBagLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plPalabra = new javax.swing.JPanel();
        btnIntentar = new javax.swing.JButton();
        btnRendir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        txtLetra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblLetrasIntentadas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNumIntentos = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        lblPalabra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        plPalabra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout plPalabraLayout = new javax.swing.GroupLayout(plPalabra);
        plPalabra.setLayout(plPalabraLayout);
        plPalabraLayout.setHorizontalGroup(
            plPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        plPalabraLayout.setVerticalGroup(
            plPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        btnIntentar.setText("Intentar");
        btnIntentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntentarActionPerformed(evt);
            }
        });

        btnRendir.setText("Rendirse");
        btnRendir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRendirActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo Juego");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jLabel1.setText("Letra a probar");

        jLabel2.setText("Letras intentadas:");

        lblLetrasIntentadas.setText("{}");

        jLabel4.setText("Intentos:");

        lblNumIntentos.setText("0");

        lblMensaje.setText("{}");

        lblPalabra.setText("{}");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRendir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIntentar))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLetra, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(plPalabra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLetrasIntentadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumIntentos)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPalabra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plPalabra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLetrasIntentadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblNumIntentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPalabra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIntentar)
                    .addComponent(btnRendir)
                    .addComponent(btnNuevo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        palabra = Palabras.MIS_PALABRAS[new Random().nextInt((Palabras.MIS_PALABRAS.length - 1) - 0 + 1)];
        System.out.println(palabra);
        comp = new Comparador(palabra, plPalabra);
        validate();
        intentos = 10;
        lblNumIntentos.setText(intentos + "");
        lblMensaje.setText("");
        lblLetrasIntentadas.setText("");
        lblPalabra.setText("");
        btnNuevo.setEnabled(false);
        btnIntentar.setEnabled(true);
        btnRendir.setEnabled(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRendirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRendirActionPerformed
        lblMensaje.setText("Descuida, No todos pueden ser triunfadores");
        lblPalabra.setText("La palabra a adivinar era: " + palabra);
        btnNuevo.setEnabled(true);
        btnIntentar.setEnabled(false);
        btnRendir.setEnabled(false);
    }//GEN-LAST:event_btnRendirActionPerformed

    private void btnIntentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntentarActionPerformed
        if (intentos <= 1) {
            lblMensaje.setText("Has perdido, no tienes mas intentos");
            lblNumIntentos.setText(--intentos + "");
            btnNuevo.setEnabled(true);
            btnIntentar.setEnabled(false);
            btnRendir.setEnabled(false);
            return;
        }
        if (!comp.encontrarLetra(txtLetra.getText().charAt(0) + "")) {
            lblNumIntentos.setText(--intentos + "");
        }

        lblLetrasIntentadas.setText(lblLetrasIntentadas.getText() + txtLetra.getText().charAt(0) + ",");
        txtLetra.setText("");

        if (revisarGanador()) {
            lblMensaje.setText("Has Ganado, Felicidades!");
            btnNuevo.setEnabled(true);
            btnIntentar.setEnabled(false);
            btnRendir.setEnabled(false);
        }
    }//GEN-LAST:event_btnIntentarActionPerformed

    private boolean revisarGanador() {
        String reArmar = "";
        for (int i = 0; i < palabra.length(); i++) {
            reArmar += ((JTextField) this.plPalabra.getComponent(i)).getText();
        }
        return palabra.equalsIgnoreCase(reArmar);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIntentar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRendir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblLetrasIntentadas;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNumIntentos;
    private javax.swing.JLabel lblPalabra;
    private javax.swing.JPanel plPalabra;
    private javax.swing.JTextField txtLetra;
    // End of variables declaration//GEN-END:variables
}
